package negocio;
// Generated 29/08/2017 22:21:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer idCargo;
     private String nome;
     private Set funcionarios = new HashSet(0);
     private Set riscosOcupacionais = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String nome) {
        this.nome = nome;
    }
    public Cargo(String nome, Set funcionarios, Set riscosOcupacionais) {
       this.nome = nome;
       this.funcionarios = funcionarios;
       this.riscosOcupacionais = riscosOcupacionais;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getRiscosOcupacionais() {
        return this.riscosOcupacionais;
    }
    
    public void setRiscosOcupacionais(Set riscosOcupacionais) {
        this.riscosOcupacionais = riscosOcupacionais;
    }




}


