package negocio;
// Generated 23/08/2017 14:17:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer idCargo;
     private String nome;
     private Set funcionarios = new HashSet(0);
     private Set riscosOcupacionaises = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String nome) {
        this.nome = nome;
    }
    public Cargo(String nome, Set funcionarios, Set riscosOcupacionaises) {
       this.nome = nome;
       this.funcionarios = funcionarios;
       this.riscosOcupacionaises = riscosOcupacionaises;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getRiscosOcupacionaises() {
        return this.riscosOcupacionaises;
    }
    
    public void setRiscosOcupacionaises(Set riscosOcupacionaises) {
        this.riscosOcupacionaises = riscosOcupacionaises;
    }




}


