package negocio;
// Generated 29/08/2017 22:21:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private Empresa empresa;
     private String cnpj;
     private String nomeFantasia;
     private String endereco;
     private String telefone;
     private Set funcionarios = new HashSet(0);
     private Set exames = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String cnpj, String nomeFantasia, String endereco, String telefone) {
        this.cnpj = cnpj;
        this.nomeFantasia = nomeFantasia;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Empresa(Empresa empresa, String cnpj, String nomeFantasia, String endereco, String telefone, Set funcionarios, Set exames, Set empresas) {
       this.empresa = empresa;
       this.cnpj = cnpj;
       this.nomeFantasia = nomeFantasia;
       this.endereco = endereco;
       this.telefone = telefone;
       this.funcionarios = funcionarios;
       this.exames = exames;
       this.empresas = empresas;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


