package negocio;
// Generated 23/08/2017 14:17:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Exame generated by hbm2java
 */
public class Exame  implements java.io.Serializable {


     private int idExame;
     private ResultadoExame resultadoExame;
     private TipoExame tipoExame;
     private String especialidade;
     private Date dataRealizacao;
     private Set funcionarios = new HashSet(0);
     private Set empresas = new HashSet(0);
     private Set atestados = new HashSet(0);

    public Exame() {
    }

	
    public Exame(int idExame, ResultadoExame resultadoExame, TipoExame tipoExame, String especialidade, Date dataRealizacao) {
        this.idExame = idExame;
        this.resultadoExame = resultadoExame;
        this.tipoExame = tipoExame;
        this.especialidade = especialidade;
        this.dataRealizacao = dataRealizacao;
    }
    public Exame(int idExame, ResultadoExame resultadoExame, TipoExame tipoExame, String especialidade, Date dataRealizacao, Set funcionarios, Set empresas, Set atestados) {
       this.idExame = idExame;
       this.resultadoExame = resultadoExame;
       this.tipoExame = tipoExame;
       this.especialidade = especialidade;
       this.dataRealizacao = dataRealizacao;
       this.funcionarios = funcionarios;
       this.empresas = empresas;
       this.atestados = atestados;
    }
   
    public int getIdExame() {
        return this.idExame;
    }
    
    public void setIdExame(int idExame) {
        this.idExame = idExame;
    }
    public ResultadoExame getResultadoExame() {
        return this.resultadoExame;
    }
    
    public void setResultadoExame(ResultadoExame resultadoExame) {
        this.resultadoExame = resultadoExame;
    }
    public TipoExame getTipoExame() {
        return this.tipoExame;
    }
    
    public void setTipoExame(TipoExame tipoExame) {
        this.tipoExame = tipoExame;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public Date getDataRealizacao() {
        return this.dataRealizacao;
    }
    
    public void setDataRealizacao(Date dataRealizacao) {
        this.dataRealizacao = dataRealizacao;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
    public Set getAtestados() {
        return this.atestados;
    }
    
    public void setAtestados(Set atestados) {
        this.atestados = atestados;
    }




}


