package negocio;
// Generated 23/08/2017 14:17:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private int crm;
     private String nome;
     private String cpf;
     private String especialidade;
     private Date dataNascimento;
     private String endereco;
     private String telefone;
     private Set atestados = new HashSet(0);

    public Medico() {
    }

	
    public Medico(int crm, String nome, String cpf, String especialidade, Date dataNascimento, String endereco) {
        this.crm = crm;
        this.nome = nome;
        this.cpf = cpf;
        this.especialidade = especialidade;
        this.dataNascimento = dataNascimento;
        this.endereco = endereco;
    }
    public Medico(int crm, String nome, String cpf, String especialidade, Date dataNascimento, String endereco, String telefone, Set atestados) {
       this.crm = crm;
       this.nome = nome;
       this.cpf = cpf;
       this.especialidade = especialidade;
       this.dataNascimento = dataNascimento;
       this.endereco = endereco;
       this.telefone = telefone;
       this.atestados = atestados;
    }
   
    public int getCrm() {
        return this.crm;
    }
    
    public void setCrm(int crm) {
        this.crm = crm;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getAtestados() {
        return this.atestados;
    }
    
    public void setAtestados(Set atestados) {
        this.atestados = atestados;
    }




}


