package negocio;
// Generated 29/08/2017 22:21:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoExame generated by hbm2java
 */
public class TipoExame  implements java.io.Serializable {


     private Integer idTipoExame;
     private String tipo;
     private Set exames = new HashSet(0);

    public TipoExame() {
    }

	
    public TipoExame(String tipo) {
        this.tipo = tipo;
    }
    public TipoExame(String tipo, Set exames) {
       this.tipo = tipo;
       this.exames = exames;
    }
   
    public TipoExame(String tipo, Integer idTipoExame) {
       this.tipo = tipo;
       this.idTipoExame = idTipoExame;
    }
    
    public Integer getIdTipoExame() {
        return this.idTipoExame;
    }
    
    public void setIdTipoExame(Integer idTipoExame) {
        this.idTipoExame = idTipoExame;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }




}


