-- MySQL Script generated by MySQL Workbench
-- 08/21/17 13:28:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemaclinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaclinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaclinica` DEFAULT CHARACTER SET latin1 ;
USE `sistemaclinica` ;

-- -----------------------------------------------------
-- Table `sistemaclinica`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`empresa` (
  `cnpj` VARCHAR(20) NOT NULL,
  `nome_fantasia` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `empresa_cnpj` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fk_empresa_empresa1_idx` (`empresa_cnpj` ASC),
  CONSTRAINT `fk_empresa_empresa1`
    FOREIGN KEY (`empresa_cnpj`)
    REFERENCES `sistemaclinica`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`funcionario` (
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `cargo_id_cargo` INT NOT NULL,
  `empresa_cnpj` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_funcionario_cargo1_idx` (`cargo_id_cargo` ASC),
  INDEX `fk_funcionario_empresa1_idx` (`empresa_cnpj` ASC),
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`cargo_id_cargo`)
    REFERENCES `sistemaclinica`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_empresa1`
    FOREIGN KEY (`empresa_cnpj`)
    REFERENCES `sistemaclinica`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`riscos_ocupacionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`riscos_ocupacionais` (
  `id_riscos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_riscos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`resultado_exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`resultado_exame` (
  `id_tipo_resultado_exame` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_resultado_exame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`tipo_exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`tipo_exame` (
  `id_tipo_exame` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_exame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`exame` (
  `id_exame` INT NOT NULL,
  `especialidade` VARCHAR(50) NOT NULL,
  `data_realizacao` DATE NOT NULL,
  `resultado_exame_id_tipo_resultado_exame` INT NOT NULL,
  `tipo_exame_id_tipo_exame` INT NOT NULL,
  PRIMARY KEY (`id_exame`),
  INDEX `fk_exame_resultado_exame1_idx` (`resultado_exame_id_tipo_resultado_exame` ASC),
  INDEX `fk_exame_tipo_exame1_idx` (`tipo_exame_id_tipo_exame` ASC),
  CONSTRAINT `fk_exame_resultado_exame1`
    FOREIGN KEY (`resultado_exame_id_tipo_resultado_exame`)
    REFERENCES `sistemaclinica`.`resultado_exame` (`id_tipo_resultado_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exame_tipo_exame1`
    FOREIGN KEY (`tipo_exame_id_tipo_exame`)
    REFERENCES `sistemaclinica`.`tipo_exame` (`id_tipo_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`medico` (
  `crm` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `especialidade` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`crm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`atestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`atestado` (
  `id_atestado` INT NOT NULL AUTO_INCREMENT,
  `resultados_riscos` VARCHAR(100) NOT NULL,
  `resultado` VARCHAR(100) NOT NULL,
  `observacoes` VARCHAR(300) NOT NULL,
  `medico_crm` INT NOT NULL,
  PRIMARY KEY (`id_atestado`),
  INDEX `fk_atestado_medico1_idx` (`medico_crm` ASC),
  CONSTRAINT `fk_atestado_medico1`
    FOREIGN KEY (`medico_crm`)
    REFERENCES `sistemaclinica`.`medico` (`crm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`cargo_has_riscos_ocupacionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`cargo_has_riscos_ocupacionais` (
  `cargo_id_cargo` INT NOT NULL,
  `riscos_ocupacionais_id_riscos` INT NOT NULL,
  PRIMARY KEY (`cargo_id_cargo`, `riscos_ocupacionais_id_riscos`),
  INDEX `fk_cargo_has_riscos_ocupacionais_riscos_ocupacionais1_idx` (`riscos_ocupacionais_id_riscos` ASC),
  INDEX `fk_cargo_has_riscos_ocupacionais_cargo_idx` (`cargo_id_cargo` ASC),
  CONSTRAINT `fk_cargo_has_riscos_ocupacionais_cargo`
    FOREIGN KEY (`cargo_id_cargo`)
    REFERENCES `sistemaclinica`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_has_riscos_ocupacionais_riscos_ocupacionais1`
    FOREIGN KEY (`riscos_ocupacionais_id_riscos`)
    REFERENCES `sistemaclinica`.`riscos_ocupacionais` (`id_riscos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`funcionario_has_exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`funcionario_has_exame` (
  `funcionario_cpf` VARCHAR(11) NOT NULL,
  `exame_id_exame` INT NOT NULL,
  PRIMARY KEY (`funcionario_cpf`, `exame_id_exame`),
  INDEX `fk_funcionario_has_exame_exame1_idx` (`exame_id_exame` ASC),
  INDEX `fk_funcionario_has_exame_funcionario1_idx` (`funcionario_cpf` ASC),
  CONSTRAINT `fk_funcionario_has_exame_funcionario1`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `sistemaclinica`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_exame_exame1`
    FOREIGN KEY (`exame_id_exame`)
    REFERENCES `sistemaclinica`.`exame` (`id_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`empresa_has_exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`empresa_has_exame` (
  `empresa_cnpj` VARCHAR(20) NOT NULL,
  `exame_id_exame` INT NOT NULL,
  PRIMARY KEY (`empresa_cnpj`, `exame_id_exame`),
  INDEX `fk_empresa_has_exame_exame1_idx` (`exame_id_exame` ASC),
  INDEX `fk_empresa_has_exame_empresa1_idx` (`empresa_cnpj` ASC),
  CONSTRAINT `fk_empresa_has_exame_empresa1`
    FOREIGN KEY (`empresa_cnpj`)
    REFERENCES `sistemaclinica`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_has_exame_exame1`
    FOREIGN KEY (`exame_id_exame`)
    REFERENCES `sistemaclinica`.`exame` (`id_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaclinica`.`exame_has_atestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaclinica`.`exame_has_atestado` (
  `exame_id_exame` INT NOT NULL,
  `atestado_id_atestado` INT NOT NULL,
  PRIMARY KEY (`exame_id_exame`, `atestado_id_atestado`),
  INDEX `fk_exame_has_atestado_atestado1_idx` (`atestado_id_atestado` ASC),
  INDEX `fk_exame_has_atestado_exame1_idx` (`exame_id_exame` ASC),
  CONSTRAINT `fk_exame_has_atestado_exame1`
    FOREIGN KEY (`exame_id_exame`)
    REFERENCES `sistemaclinica`.`exame` (`id_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exame_has_atestado_atestado1`
    FOREIGN KEY (`atestado_id_atestado`)
    REFERENCES `sistemaclinica`.`atestado` (`id_atestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
