package negocio;
// Generated 21/08/2017 13:54:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Atestado generated by hbm2java
 */
public class Atestado  implements java.io.Serializable {


     private Integer idAtestado;
     private Medico medico;
     private String resultadosRiscos;
     private String resultado;
     private String observacoes;
     private Set exames = new HashSet(0);

    public Atestado() {
    }

	
    public Atestado(Medico medico, String resultadosRiscos, String resultado, String observacoes) {
        this.medico = medico;
        this.resultadosRiscos = resultadosRiscos;
        this.resultado = resultado;
        this.observacoes = observacoes;
    }
    public Atestado(Medico medico, String resultadosRiscos, String resultado, String observacoes, Set exames) {
       this.medico = medico;
       this.resultadosRiscos = resultadosRiscos;
       this.resultado = resultado;
       this.observacoes = observacoes;
       this.exames = exames;
    }
   
    public Integer getIdAtestado() {
        return this.idAtestado;
    }
    
    public void setIdAtestado(Integer idAtestado) {
        this.idAtestado = idAtestado;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public String getResultadosRiscos() {
        return this.resultadosRiscos;
    }
    
    public void setResultadosRiscos(String resultadosRiscos) {
        this.resultadosRiscos = resultadosRiscos;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }




}


