package negocio;
// Generated 21/08/2017 13:54:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RiscosOcupacionais generated by hbm2java
 */
public class RiscosOcupacionais  implements java.io.Serializable {


     private Integer idRiscos;
     private String nome;
     private Set cargos = new HashSet(0);

    public RiscosOcupacionais() {
    }

	
    public RiscosOcupacionais(String nome) {
        this.nome = nome;
    }
    public RiscosOcupacionais(String nome, Set cargos) {
       this.nome = nome;
       this.cargos = cargos;
    }
   
    public Integer getIdRiscos() {
        return this.idRiscos;
    }
    
    public void setIdRiscos(Integer idRiscos) {
        this.idRiscos = idRiscos;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set cargos) {
        this.cargos = cargos;
    }




}


